spring.application.name=SafePlate
# Use local profile by default
spring.profiles.active=local
# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Liquibase Settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
ai-server.url=https://hn-ui-gdg-team-9.hf.space/
# JWT Settings
jwt.secret=${JWT_SECRET:local-dev-secret-key-must-be-32-chars}
jwt.expiration=${JWT_EXPIRATION:3600000}

# avoid item url
avoid.ai.url=# //AVOID-AI-ENDPOINT